#This template will handle receivers stop sending command and waiting for receivers to be in status DOWN
parameters:
  # deployment environment
  - name: ENV
    type: string
    values:
      - DEV
      - UAT
      - PROD
  # command target deployment version
  - name: TARGET_DEPLOYMENT_VERSION
    type: string
    values:
      - PROD
      - STAGING
  # service api key to be used in command requests
  - name: SERVICE_API_KEY
    type: string

steps:
  - template: receivers-commands/send-receiver-command.yml
    parameters:
      ENV: ${{ parameters.ENV }}
      COMMAND: STOP
      TARGET_DEPLOYMENT_VERSION: ${{ parameters.TARGET_DEPLOYMENT_VERSION }}
      SERVICE_API_KEY: ${{ parameters.SERVICE_API_KEY }}
  - template: receivers-commands/polling-receivers-status.yml
    parameters:
      ENV: ${{ parameters.ENV }}
      WANTED_STATUS: DOWN
      TARGET_DEPLOYMENT_VERSION: ${{ parameters.TARGET_DEPLOYMENT_VERSION }}
      SERVICE_API_KEY: ${{ parameters.SERVICE_API_KEY }}